baseURL = 'https://example.org/'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'Okay Decals'
theme = 'lynx'
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
name = "Okay Projects"
headline = "I make art and tech projects. They're okay. Okay projects"
image = "imgs/okay_decals.png"            # path relative to static directory

links = [
    { link = { href = "https://okayprojects.etsy.com", text = "Etsy" } },
    { instagram = "https://www.instagram.com/okay.projects/" },
]

[module]
[module.hugoVersion]
extended = false
min = "0.86.1"
