baseURL = 'https://okyang.github.io'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'Okay Projects'
theme = 'lynx'
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
name = "Okay Projects"
headline = "I make art and tech projects. They're okay. Okay projects"
image = "imgs/okay_decals.png"            # path relative to static directory

links = [
    { link = { href = "https://okayprojects.etsy.com", text = "Etsy" } },
    { instagram = "https://www.instagram.com/okay.projects/" },
    { youtube = "https://www.youtube.com/channel/UC1w2IIKQ_bqi_ST5ZaK68vg" },
    { link = { href = "https://okyang.github.io/", text = "okyang.github.io"}},
    { link = { href = "https://www.instructables.com/member/OwenY1", text = "Instructables"}},
    { link = { href = "https://www.hackster.io/owenyang123", text = "Hackster.io"}},
]

[module]
[module.hugoVersion]
extended = false
min = "0.86.1"
